services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: senhasecreta
      POSTGRES_DB: stockflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stockflow-network

  test-db:
    image: postgres:13
    ports:
      - "5433:5432"  # Evita conflito com dev-db
    environment:
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: senhasecreta
      POSTGRES_DB: stockflow_db
    networks:
      - stockflow-network
networks:
  stockflow-network:

volumes:
  pgdata:

