services:
  dev-db:
    image: postgres:13
    container_name: container-db
    ports:
      - "5432:5432"
    profiles: ["test", "develop", "build"]
    environment:
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: senhasecreta
      POSTGRES_DB: stockflow_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockflow -d stockflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stockflow-network
  backend-test:
    build:
      context: .
      target: test
    container_name: container-backend
    profiles: ["test"]
    ports:
        - "3001:3000"
    command: /bin/sh -c "npx prisma migrate deploy && npm run test:e2e" #Só para testes, não mexer, se precisa deixar rodando, usar o backend-dev ou o backend-build
    depends_on:
      dev-db:
        condition: service_healthy

    networks:
       - stockflow-network
    environment:
       - DATABASE_URL=postgresql://stockflow:senhasecreta@dev-db:5432/stockflow_db?schema=public
  backend-dev:
    build:
      context: .
      target: test
    profiles: ["develop"]
    container_name: container-backend
    ports:
        - "3001:3000"
    command: /bin/sh -c "npx prisma migrate dev && npm run start:dev"
    depends_on:
      dev-db:
        condition: service_healthy

    networks:
       - stockflow-network
    environment:
       - DATABASE_URL=postgresql://stockflow:senhasecreta@dev-db:5432/stockflow_db?schema=public
  backend-build:
    build:
      context: .
      target: prod
    profiles: ["build"]
    container_name: container-backend
    ports:
        - "3001:3000"
    depends_on:
      dev-db:
        condition: service_healthy

    networks:
       - stockflow-network
    environment:
       - DATABASE_URL=${DATABASE_URL}



networks:
  stockflow-network:
