name: Build and push docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Login in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build docker image
        run: | 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/stockflow:${GITHUB_SHA} .
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/stockflow:${GITHUB_SHA}
      - name: Update Terraform Cloud variable
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/stockflow:${GITHUB_SHA}
        run: |
          # Pega o ID do workspace
          WORKSPACE_ID=$(curl -s \
            -H "Authorization: Bearer $TFC_TOKEN" \
            -H "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/organizations/minha-org/workspaces/stockflow-workspace \
            | jq -r '.data.id')

          # Pega o ID da variável backend_image
          VAR_ID=$(curl -s \
            -H "Authorization: Bearer $TFC_TOKEN" \
            -H "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/vars \
            | jq -r '.data[] | select(.attributes.key=="backend_image") | .id')

          # Atualiza a variável com a nova imagem
          curl -s \
            -X PATCH \
            -H "Authorization: Bearer $TFC_TOKEN" \
            -H "Content-Type: application/vnd.api+json" \
            -d "{\"data\":{\"id\":\"$VAR_ID\",\"type\":\"vars\",\"attributes\":{\"value\":\"$IMAGE_TAG\",\"hcl\":false,\"category\":\"terraform\"}}}" \
            https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/vars
